// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxdzwhdbvqjvsthevbxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54ZHp3aGRidnFqdnN0aGV2YnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTMzMTYsImV4cCI6MjA2OTgyOTMxNn0.mNx0RqiMlHRowGyKw28el2Es3L-w0xCiYp17qjAN2SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});